### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by buzzbo** [96AA48/gmplayer#22]
Just updated and this is all I get when I run `gmp`

````/usr/local/lib/node_modules/gmplayer/app.js:19
cli.main((args, options) => {
                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
````

**Comment by 96AA48** [comment]
Your node version is outdated and doesn't support lexical ECMAScript 2016.
If you update your Node.js installation the issue should resolve.

**Comment by buzzbo** [comment]
Ah thanks. Updated node and it's working now.
