### ISSUE TITLE
Handle songs with slashes in the track title

### ISSUE THREAD

**Issue by Widdershin** [96AA48/gmplayer#4]
Currently, trying to play a song that contains a `/` in the name will crash gmplayer.

Steps to reproduce:

```
 λ ./gmplayer -s The Beyond flying lotus
Looking up requested song -
[0] Your Potential//The Beyond (feat. Niki Randa) - Flying Lotus
What song do you want to play? #0

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/nickj/Music/Your Potential/The Beyond (feat. Niki Randa) - Flying Lotus.mp3'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at IncomingMessage.<anonymous> (/Users/nickj/Projects/gmplayer/app.js:203:14)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at TLSSocket.socketOnData (_http_client.js:305:20)
```

We should probably sanitize the filename before saving. Maybe https://www.npmjs.com/package/sanitize-filename? (seems like it might be overkill)

**Comment by 96AA48** [comment]
I have a function called makeSafe in yplayer that we can use. It just does a regex replace. (replaces "/" or "\" with "|"). Sound good? or do we need something more subtle?

**Comment by 96AA48** [comment]
Here's the implementation I did for yplayer that I referenced:
```javascript
function makeSafe(str) {
  return str.replace(/\//g, '|');
}
```
